
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # http://${eureka.instance.hostname}:${server.port}/eureka/ # 注册中心url
spring:
  application:
    name: eurka-server  #服务名称
    
server:
  port: 8082 # 服务端口
